#############################################################################
# Makefile for building: GenWData
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 7? 24 11:55:49 2013
# Project:  ../GenWData/GenWData.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-4.8.4/bin/qmake -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../GenWData/GenWData.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ -I../GenWData -I/usr/local/Trolltech/Qt-4.8.4/include/QtCore -I/usr/local/Trolltech/Qt-4.8.4/include/QtGui -I/usr/local/Trolltech/Qt-4.8.4/include -I/usr/local/qwt-6.1.0-rc3/include -I. -I. -I../GenWData -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/Trolltech/Qt-4.8.4/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-4.8.4/lib -L/home/mars/Qtprj/GenWData/../../../../usr/local/qwt-6.1.0-rc3/lib/ -lqwt -lQtGui -L/usr/local/Trolltech/Qt-4.8.4/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-4.8.4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../GenWData/main.cpp \
		../GenWData/mwgenwdata.cpp moc_mwgenwdata.cpp
OBJECTS       = main.o \
		mwgenwdata.o \
		moc_mwgenwdata.o
DIST          = /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		../GenWData/GenWData.pro
QMAKE_TARGET  = GenWData
DESTDIR       = 
TARGET        = GenWData

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mwgenwdata.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: ../GenWData/GenWData.pro  /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++/qmake.conf /usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/declarative_debug.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl
	$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../GenWData/GenWData.pro
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/debug.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/declarative_debug.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.4/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-4.8.4/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Trolltech/Qt-4.8.4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile ../GenWData/GenWData.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/GenWData1.0.0 || $(MKDIR) .tmp/GenWData1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/GenWData1.0.0/ && $(COPY_FILE) --parents ../GenWData/mwgenwdata.h .tmp/GenWData1.0.0/ && $(COPY_FILE) --parents ../GenWData/main.cpp ../GenWData/mwgenwdata.cpp .tmp/GenWData1.0.0/ && $(COPY_FILE) --parents ../GenWData/mwgenwdata.ui .tmp/GenWData1.0.0/ && (cd `dirname .tmp/GenWData1.0.0` && $(TAR) GenWData1.0.0.tar GenWData1.0.0 && $(COMPRESS) GenWData1.0.0.tar) && $(MOVE) `dirname .tmp/GenWData1.0.0`/GenWData1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/GenWData1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mwgenwdata.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mwgenwdata.cpp
moc_mwgenwdata.cpp: /usr/local/qwt-6.1.0-rc3/include/qwt_plot.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_global.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_text.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_graphic.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_transform.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_interval.h \
		../GenWData/mwgenwdata.h
	/usr/local/Trolltech/Qt-4.8.4/bin/moc $(DEFINES) $(INCPATH) ../GenWData/mwgenwdata.h -o moc_mwgenwdata.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mwgenwdata.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mwgenwdata.h
ui_mwgenwdata.h: ../GenWData/mwgenwdata.ui \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_global.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_text.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_graphic.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_transform.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_interval.h
	/usr/local/Trolltech/Qt-4.8.4/bin/uic ../GenWData/mwgenwdata.ui -o ui_mwgenwdata.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../GenWData/main.cpp ../GenWData/mwgenwdata.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_global.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_text.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_graphic.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_transform.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_interval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../GenWData/main.cpp

mwgenwdata.o: ../GenWData/mwgenwdata.cpp ../GenWData/mwgenwdata.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_global.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_text.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_plot_item.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_legend_data.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_graphic.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_scale_map.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_transform.h \
		/usr/local/qwt-6.1.0-rc3/include/qwt_interval.h \
		ui_mwgenwdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mwgenwdata.o ../GenWData/mwgenwdata.cpp

moc_mwgenwdata.o: moc_mwgenwdata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mwgenwdata.o moc_mwgenwdata.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

